export const blogPost = [
  {
    author: "Temitope Quadri",
    photo: "/team.jpeg",
    body: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident laborum veniam reprehenderit, omnis eaque quod unde, nihil ad quos dolores magnam nesciunt deserunt architecto ut exercitationem rerum, molestiae minima quam numquam totam harum dolorum laudantium sapiente asperiores? Cupiditate harum vero autem modi unde delectus repudiandae corrupti cum. Saepe omnis molestiae illo porro maiores veniam ipsa quo, perferendis quia architecto tempora quibusdam, esse molestias. Quis beatae labore architecto vel nostrum. Dolor ex sapiente, corrupti quaerat maiores doloribus cumque nostrum pariatur sit, libero temporibus dolorem iure nam recusandae amet illum. Aliquam unde debitis culpa nostrum vitae illum delectus velit. Sunt, eius, quod alias tenetur quasi labore consequatur eos recusandae ullam id aperiam iure, dolorem illum neque eum officia consequuntur unde. Unde dolores harum quae ad repellat rerum fugiat, officiis dolorem sunt libero alias, eveniet voluptatibus quia voluptate, magni dolor vel ratione. Impedit nihil ut itaque quidem illum quas facilis dolorum consequatur neque ea eveniet ipsa debitis dicta sapiente vel incidunt ratione, cupiditate reiciendis voluptatibus eum minus iure aperiam, amet nemo. Tenetur ut consectetur, ipsam minus atque unde modi nihil iure cum, perspiciatis possimus, consequatur fugit a qui quia distinctio explicabo magnam cumque placeat. Culpa tempora debitis ad. Quaerat consectetur culpa sunt voluptas!",
    subTitle: "The way to go!",
    title: "How to successfully log in to OGSoft solutions account",
    date: new Date,
    _id: "1215442",
  },
  {
    author: "Jessica Agbala",
    photo: "/team.jpeg",
    body: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident laborum veniam reprehenderit, omnis eaque quod unde, nihil ad quos dolores magnam nesciunt deserunt architecto ut exercitationem rerum, molestiae minima quam numquam totam harum dolorum laudantium sapiente asperiores? Cupiditate harum vero autem modi unde delectus repudiandae corrupti cum. Saepe omnis molestiae illo porro maiores veniam ipsa quo, perferendis quia architecto tempora quibusdam, esse molestias. Quis beatae labore architecto vel nostrum. Dolor ex sapiente, corrupti quaerat maiores doloribus cumque nostrum pariatur sit, libero temporibus dolorem iure nam recusandae amet illum. Aliquam unde debitis culpa nostrum vitae illum delectus velit. Sunt, eius, quod alias tenetur quasi labore consequatur eos recusandae ullam id aperiam iure, dolorem illum neque eum officia consequuntur unde. Unde dolores harum quae ad repellat rerum fugiat, officiis dolorem sunt libero alias, eveniet voluptatibus quia voluptate, magni dolor vel ratione. Impedit nihil ut itaque quidem illum quas facilis dolorum consequatur neque ea eveniet ipsa debitis dicta sapiente vel incidunt ratione, cupiditate reiciendis voluptatibus eum minus iure aperiam, amet nemo. Tenetur ut consectetur, ipsam minus atque unde modi nihil iure cum, perspiciatis possimus, consequatur fugit a qui quia distinctio explicabo magnam cumque placeat. Culpa tempora debitis ad. Quaerat consectetur culpa sunt voluptas!",
    subTitle: "The way to go!",
    title: "How to successfully log in to OGSoft solutions account1",
    date: new Date,
    _id: "1225457",
  },
  {
    author: "Ogomebuneme Adigwe",
    photo: "/team.jpeg",
    body: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident laborum veniam reprehenderit, omnis eaque quod unde, nihil ad quos dolores magnam nesciunt deserunt architecto ut exercitationem rerum, molestiae minima quam numquam totam harum dolorum laudantium sapiente asperiores? Cupiditate harum vero autem modi unde delectus repudiandae corrupti cum. Saepe omnis molestiae illo porro maiores veniam ipsa quo, perferendis quia architecto tempora quibusdam, esse molestias. Quis beatae labore architecto vel nostrum. Dolor ex sapiente, corrupti quaerat maiores doloribus cumque nostrum pariatur sit, libero temporibus dolorem iure nam recusandae amet illum. Aliquam unde debitis culpa nostrum vitae illum delectus velit. Sunt, eius, quod alias tenetur quasi labore consequatur eos recusandae ullam id aperiam iure, dolorem illum neque eum officia consequuntur unde. Unde dolores harum quae ad repellat rerum fugiat, officiis dolorem sunt libero alias, eveniet voluptatibus quia voluptate, magni dolor vel ratione. Impedit nihil ut itaque quidem illum quas facilis dolorum consequatur neque ea eveniet ipsa debitis dicta sapiente vel incidunt ratione, cupiditate reiciendis voluptatibus eum minus iure aperiam, amet nemo. Tenetur ut consectetur, ipsam minus atque unde modi nihil iure cum, perspiciatis possimus, consequatur fugit a qui quia distinctio explicabo magnam cumque placeat. Culpa tempora debitis ad. Quaerat consectetur culpa sunt voluptas!",
    subTitle: "The way to go!",
    title: "How to successfully log in to OGSoft solutions account2",
    date: new Date,
    _id: "12188",
  },
  {
    author: "Chukumela Wilson",
    photo: "/team.jpeg",
    body: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident laborum veniam reprehenderit, omnis eaque quod unde, nihil ad quos dolores magnam nesciunt deserunt architecto ut exercitationem rerum, molestiae minima quam numquam totam harum dolorum laudantium sapiente asperiores? Cupiditate harum vero autem modi unde delectus repudiandae corrupti cum. Saepe omnis molestiae illo porro maiores veniam ipsa quo, perferendis quia architecto tempora quibusdam, esse molestias. Quis beatae labore architecto vel nostrum. Dolor ex sapiente, corrupti quaerat maiores doloribus cumque nostrum pariatur sit, libero temporibus dolorem iure nam recusandae amet illum. Aliquam unde debitis culpa nostrum vitae illum delectus velit. Sunt, eius, quod alias tenetur quasi labore consequatur eos recusandae ullam id aperiam iure, dolorem illum neque eum officia consequuntur unde. Unde dolores harum quae ad repellat rerum fugiat, officiis dolorem sunt libero alias, eveniet voluptatibus quia voluptate, magni dolor vel ratione. Impedit nihil ut itaque quidem illum quas facilis dolorum consequatur neque ea eveniet ipsa debitis dicta sapiente vel incidunt ratione, cupiditate reiciendis voluptatibus eum minus iure aperiam, amet nemo. Tenetur ut consectetur, ipsam minus atque unde modi nihil iure cum, perspiciatis possimus, consequatur fugit a qui quia distinctio explicabo magnam cumque placeat. Culpa tempora debitis ad. Quaerat consectetur culpa sunt voluptas!",
    subTitle: "The way to go!",
    title: "How to successfully log in to OGSoft solutions account3",
    date: new Date,
    _id: "12142",
  },
  {
    author: "Chukumela Wilson",
    photo: "/team.jpeg",
    body: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Provident laborum veniam reprehenderit, omnis eaque quod unde, nihil ad quos dolores magnam nesciunt deserunt architecto ut exercitationem rerum, molestiae minima quam numquam totam harum dolorum laudantium sapiente asperiores? Cupiditate harum vero autem modi unde delectus repudiandae corrupti cum. Saepe omnis molestiae illo porro maiores veniam ipsa quo, perferendis quia architecto tempora quibusdam, esse molestias. Quis beatae labore architecto vel nostrum. Dolor ex sapiente, corrupti quaerat maiores doloribus cumque nostrum pariatur sit, libero temporibus dolorem iure nam recusandae amet illum. Aliquam unde debitis culpa nostrum vitae illum delectus velit. Sunt, eius, quod alias tenetur quasi labore consequatur eos recusandae ullam id aperiam iure, dolorem illum neque eum officia consequuntur unde. Unde dolores harum quae ad repellat rerum fugiat, officiis dolorem sunt libero alias, eveniet voluptatibus quia voluptate, magni dolor vel ratione. Impedit nihil ut itaque quidem illum quas facilis dolorum consequatur neque ea eveniet ipsa debitis dicta sapiente vel incidunt ratione, cupiditate reiciendis voluptatibus eum minus iure aperiam, amet nemo. Tenetur ut consectetur, ipsam minus atque unde modi nihil iure cum, perspiciatis possimus, consequatur fugit a qui quia distinctio explicabo magnam cumque placeat. Culpa tempora debitis ad. Quaerat consectetur culpa sunt voluptas!",
    subTitle: "The way to go!",
    title: "How to successfully log in to OGSoft solutions account4",
    date: new Date,
    _id: "12124564",
  },
];
